Ft  basic UI
Bateyjosue/School_Library_OOP pull request #4
Opened 2022-11-11 12:33 UTC by Bateyjosue

# FEATURE DESCRIPTION
## TASK:
In this project, I create a form of UI for our school library app. This way it can be invoked as an executable and not something you use in IRB exclusively.
![ScreenShot](./screenshot.png)

### Cheers

# Happy Review

2022-11-11 12:50 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Josh, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
README is professional. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-11 12:50 UTC, SajjadAhmad14 commented on main.rb
> +def list_rental()
There is an error when the user tries to list all rentals. Kindly see the screenshot below.

![rent](https://user-images.githubusercontent.com/35504149/201343954-d2e02126-d10f-43e5-b0a5-4ca7ae01324e.png)

2022-11-11 13:38 UTC, Bateyjosue commented on main.rb
> +def list_rental()
Oh okay. Thanks, Bro. Thanks, I messed up when fixing linters... 
Gotcha

Let me work on it...

2022-11-12 13:52 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 13:56 UTC, merged