Ft  preserve data
Bateyjosue/School_Library_OOP pull request #6
Opened 2022-11-23 10:45 UTC by Bateyjosue

# FEATURE DESCRIPTION

## TASK

In this project, we preserve the data from our app and load preserved data on startup.

## Cheers

# Happy Review

2022-11-23 16:01 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @AlierPM, @Bateyjosue :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following GitFlow
✔️ Following some requirements

Good job on implementing some of the reqirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 16:01 UTC, HAMMAS-SALEEM commented on app.rb
>      puts '7 - Exit'
![image](https://user-images.githubusercontent.com/93039359/203590796-f322e7f0-3265-4dbe-be3c-e868b6001c2b.png)

- [ ] After creating books or person or rentals when we quit the application in the terminal then it shows this error and doesn't make any change in the data json files :fearful: Kindly fix this issue :blush:

2022-11-23 16:01 UTC, HAMMAS-SALEEM commented on app.rb
>    end
![image](https://user-images.githubusercontent.com/93039359/203591362-8af98e59-d725-409d-8c5e-4093297d288d.png)

- [ ] When we start the application without having data json files then your application shows this error shown above :arrow_up: so your application should see that if book.json file or rental.json or person.json file doesn't exist then your application should create these files before initializing the application :blush:

2022-11-24 07:56 UTC, arslanbisharat commented
Hi @Bateyjosue,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 10:37 UTC, merged